# Generated by Django 2.1.2 on 2018-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('L', 'Logic'), ('P', 'Probability'), ('C', 'Calculus'), ('GF', 'Geometry fundamental'), ('CS', 'Computer science')], max_length=100)),
                ('counter', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
    ]
