# Generated by Django 2.1.2 on 2018-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20181107_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('fullName', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(choices=[('Vietnam', 'Vietnam'), ('England', 'England'), ('America', 'America'), ('Japan', 'Japan')], max_length=100)),
                ('education', models.CharField(max_length=40)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
